//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM_BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int book_ID { get; set; }
        public string book_title { get; set; }
        public string book_summary { get; set; }
        public string book_image { get; set; }
        public float book_price { get; set; }
        public int book_quantityInStorage { get; set; }
        public int book_numOfPages { get; set; }
        public byte book_status { get; set; }
        public int book_author { get; set; }
        public int book_publisher { get; set; }
        public int book_rating { get; set; }
        public int book_type { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Type Type { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
