//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM_BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int orderInfo_book { get; set; }
        public int orderInfo_order { get; set; }
        public int orderInfo_quantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
